### ISSUE TITLE
Can't control speed anymore?

### ISSUE THREAD

**Issue by peteruithoven** [LaosLaser/Firmware#20]
Using version master.fbcd2b0-dirty.bin we can engrave several times faster than we used to, but it seems like we can't control the speed anymore. There's no difference between a job at 100% vs. 0.01% speed

The speed ends up correctly in the simplecode. I've added the beginning of a simple engrave job below. Parameter 100 should be the speed, which is set to 1 which represents 0.01%. 
```
201 9906
202 59816
203 505141
204 510094
7 100 1
7 101 10000
0 5841 319839
```

**Comment by matthijskooijman** [comment]
Isn't this what a859d18faa9030d29feff51f32e71c7b05f2eab2 fixes? @peteruithoven

**Comment by peteruithoven** [comment]
Yep it should, thanks for the reminder. 
Please reopen the issue if it didn't fix the issue.
