### ISSUE TITLE
laser_enable pin doesnt do anything

### ISSUE THREAD

**Issue by thinkl33t** [LaosLaser/Firmware#47]
Are there any plans to make the laser_enable pin do anything?  

I would like to use it as part of our access control system, with it turning on at the beginning of the job, and off at the end (which is what laser_enable would do anyway I think).

It could also be used for control of the air assist pump.

**Comment by ccreutzig** [comment]
Would it not be easier for an access mechanism to hook into the door-open line (in serial, such that the driver thinks the door is open when it is *or* when the access control says not to run)?
Changing the config file means you'd have to also reset the laser cutter, I believe.

**Comment by thinkl33t** [comment]
That is how we currently prevent the laser from firing when a valid user hasn't scanned into the cutter.

The functionality above adds a feedback channel, so we know when the laser tube is being used.  As we charge for laser cutter time, we plan on detecting this and automatically charging it to the user's account.

**Comment by thinkl33t** [comment]
This is now implemented
