### ISSUE TITLE
Problem with config.txt speed and real speed running

### ISSUE THREAD

**Issue by JSilvaGlez** [LaosLaser/Firmware#55]
We've detected that do not match the speeds set in the config.txt file with actually speed running the machine.
You would know tell me why ?  The configuration scale is correct should be fine ?.

I would like to explain and to correct this error.

**Comment by jrv** [comment]
I think this is more an issue to discuss on the forum: http://redmine.laoslaser.org/projects/laos/boards
Many experienced users there...
