### ISSUE TITLE
Docs installing python-colorama

### ISSUE THREAD

**Issue by peteruithoven** [LaosLaser/Firmware#57]
The readme mentiones installing python-colorama, but doesn't explain how. For people not familiar with python it would be good to explain this. 
I installed pip (python package manager) and used that to install colorama. 
``` bash
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install colorama
```

**Comment by peteruithoven** [comment]
(python-colorama is not found on port (OS X, apt-get like package manager)

**Comment by peteruithoven** [comment]
Another way of installing, that doesn't require `pip` seems to be to 
1. download it manually from: https://pypi.python.org/pypi/colorama/0.3.3
2. Extracting it 
3. Running `python setup.py install` inside it.

**Comment by matthijskooijman** [comment]
On Debian (and probably also Ubuntu), you can install the python-colorama (or python3-colorama) package.

**Comment by jrv** [comment]
Feel free to update the documentation on using mbed libraries, but problems installing MBED libs are not LaOS problems.

**Comment by peteruithoven** [comment]
They kind of are if they increase the barrier to entry
