### ISSUE TITLE
Incorrect implementation of TFTP?

### ISSUE THREAD

**Issue by t-oster** [LaosLaser/Firmware#63]
Hi,
some of our users have a problem which boils down to LAOS TFTP server not correctly working with apache commons-net TFTP client.
See here: https://github.com/t-oster/LibLaserCut/issues/131
It seems as if the LAOS tftp will answer from port 69, which should not be the case according to https://issues.apache.org/jira/browse/NET-414 (`an incorrectly written TFTP server replies to a request from a control socket instead of building a new socket that attaches to an ephemeral port`).

Maybe there is an easy fix for the LAOS firmware? Otherwise we will have to patch commons-net for VisiCut to work, I don't think they will revert their check.

**Comment by pbrier** [comment]
Should be fixed in latest release. Tested against Visicut 1.9.41-ge370801a
Try this  firmware: [laoslaser-2020-03-23-a459d9.bin](https://github.com/LaosLaser/Firmware/blob/master/laoslaser-2020-03-23-a459d9.bin)

**Comment by t-oster** [comment]
Thanks @pbrier, nice to hear you're still in business.

**Comment by pbrier** [comment]
Making my laser covid19 ready. I would not recommend to upgrade your firmware in a crises, but if you need: now it should work with the latest Visicut again.@t-oster:  Did you test it?

**Comment by t-oster** [comment]
@pbrier no, but I trust in you ;). My lasercutter is not very busy atm.

**Comment by peteruithoven** [comment]
(It might be a good idea to create a Release, that way people can easily get notified (after watching "Releases only")

It's great to see you both are still keeping things up to date :) I understood Fablab Amersfoort had to use an old version of Visicut because of this issue.

**Comment by dirkx** [comment]
Should work - our change at makerspaceleiden.nl was virtually the same - except we also block a new incoming during the send port being active.

**Comment by PieterBosNr1** [comment]
Thank u so much !!
Never upgraded the firmware after first installing it :-|
After the update it did not start up  (stuck at start screen)
I fixed it by upgrading the mbed LPC1768 firmware from 16457 to  141212

https://os.mbed.com/handbook/Firmware-LPC1768-LPC11U24

**Comment by MartiniMoe** [comment]
Hi @PieterBosNr1 
I am facing the same problem, can you please tell me, how you updated the MBED Firmware? Isnt it compiled into the LAOS firmware?

Thanks!

**Comment by PieterBosNr1** [comment]
Hi @MartiniMoe 
as far i can tel it is not (but i clould be wrong), so what i did was:
connent de mbed. drag de firmware file to the mounted drive. 
disconnect en and connected de usb cable. after a short time de firmware should updated.

But is was stil having problems with it (not connecting at al)

Went ahead a bought a new brain for the laser i wanted the cohesion board but that was not avalable at the time (https://cohesion3d.com/)
So i  got the awesome tech mini gerbil [mg3-mini-gerbil](https://awesome.tech/product/mg3-mini-gerbil-v3-2-axis-controller-for-k40-laser/). This one also works with lightburn (which is worth every penny).


Hope this helps
